# Generated by Django 5.1.2 on 2024-10-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_id",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=True,
                verbose_name="ID пользователя в телеграм",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tg_username",
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                unique=True,
                verbose_name="username пользователя в телеграм",
            ),
        ),
    ]
