# Generated by Django 5.1.2 on 2024-10-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_tg_id_user_tg_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tg_username",
            field=models.CharField(
                help_text="Укажите свой username в Telegram",
                max_length=30,
                unique=True,
                verbose_name="username пользователя в телеграм",
            ),
        ),
    ]
