# Generated by Django 5.1.2 on 2024-10-24 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Место"
                    ),
                ),
                (
                    "time_of_action",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Время"
                    ),
                ),
                ("action", models.CharField(max_length=200, verbose_name="Действие")),
                (
                    "is_pleasure",
                    models.BooleanField(
                        default=False, verbose_name="Признак приятной привычки"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("DAILY", "every day"),
                            ("TWO", "every two days"),
                            ("THREE", "every three days"),
                            ("WEEKLY", "once a week"),
                        ],
                        max_length=6,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.SmallIntegerField(
                        blank=True,
                        default=120,
                        null=True,
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "bound_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите приятную привычку",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="good_habit.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Полезная привычка",
                "verbose_name_plural": "Полезные привычки",
                "ordering": ["owner"],
            },
        ),
    ]
