# Generated by Django 5.1.2 on 2024-10-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("good_habit", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="time_to_complete",
        ),
        migrations.AddField(
            model_name="habit",
            name="time_to_perform",
            field=models.SmallIntegerField(
                default=120,
                help_text="Укажите время на выполнение в секундах",
                verbose_name="Время на выполнение",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.SmallIntegerField(
                default=1,
                help_text="Укажите периодичность выполнения привычки в днях",
                verbose_name="Периодичность",
            ),
        ),
    ]
