# Generated by Django 5.1.2 on 2024-10-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "good_habit",
            "0003_remove_habit_time_to_complete_habit_time_to_perform_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="first_date",
            field=models.DateField(
                blank=True,
                help_text="Укажите дату первого выполнения привычки",
                null=True,
                verbose_name="Дата первого выполнения",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_of_action",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Время выполнения привычки"
            ),
        ),
    ]
