# Generated by Django 5.1.2 on 2024-10-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("good_habit", "0004_habit_first_date_alter_habit_time_of_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="time_of_action",
            field=models.TimeField(
                blank=True,
                help_text="Укажите время выполнения привычки в секундах",
                null=True,
                verbose_name="Время выполнения привычки",
            ),
        ),
    ]
